### ISSUE TITLE
Transaction fails when contract creation

### ISSUE THREAD

**Issue by ptrcarta** [flashbots/rpc-endpoint#101]
When using the flashbots-protect endpoint (`https://rpc.flashbots.net`), the network request fails (code `502`) if the transaction is a contract creation. I haven't run the server myself, but I believe this line might be responsible (assumes `r.tx.To() != Nil`)
https://github.com/flashbots/rpc-endpoint/blob/4804d685ea63c42e92cee627e7bb226f305fe038/server/request_sendrawtx.go#L94

and this one too

https://github.com/flashbots/rpc-endpoint/blob/4804d685ea63c42e92cee627e7bb226f305fe038/server/request_sendrawtx.go#L97

**Comment by bhakiyakalimuthu** [comment]
@ptrcarta thank you for reporting this. fixed in this PR.
https://github.com/flashbots/rpc-endpoint/pull/106
https://github.com/flashbots/rpc-endpoint/pull/109
