### ISSUE TITLE
flashbots_getBundleStats fails with "data did not match any variant of untagged enum ResponseData"

### ISSUE THREAD

**Issue by ibhagwan** [flashbots/rpc-endpoint#108]
I'm not sure if this is the correct repo for this issue but it seemed the most fitting out of the exisiting flashbots repos, please redirect me to the right repo if this is not the place for it.

As per the title, when sending bundles to `https://relay-goerli.flashbots.net`, calling `flashbots_getBundleStats` returns the below error:
```
RelayError(
  ResponseSerdeJson {
    err: Error("data did not match any variant of untagged enum ResponseData", line: 1, column: 55),
    text: "{\"id\":6,\"result\":{\"isSimulated\":false},\"jsonrpc\":\"2.0\"}",
  }
```

I tried using both bundles that aren't included and also bundles that end up being included both fail with the same above error.

Although I’m not sure yet  if related, it's worth noting I'm using [ethers-flashbots](https://github.com/onbjerg/ethers-flashbots) to perform the request.

**Comment by bhakiyakalimuthu** [comment]
Hi thank you for reporting this issue. We updated bundle stats endpoint to include pos changes.we updated ethers-flashbots. But I can double check whether it is released or not. could you please ping in FB Dicord channel going forward (Probably you might have but missed in the flood of messages). Will look into it,WIll close this issue here for now.

**Comment by ibhagwan** [comment]
> @ibhagwan thank you for reporting this issue. We updated bundle stats endpoint to include pos changes.we updated ethers-flashbots. But I can double check whether it is released or not. could you please ping in FB Dicord channel going forward (Probably you might have but missed in the flood of messages). Will look into it,WIll close this issue here for now.

I actually posted this on discord in multiple channels and received no response, check out my message in #mev-boost from yesterday.

**Comment by ibhagwan** [comment]
> @ibhagwan thank you for reporting this issue. We updated bundle stats endpoint to include pos changes.we updated ethers-flashbots. But I can double check whether it is released or not. could you please ping in FB Dicord channel going forward (Probably you might have but missed in the flood of messages). Will look into it,WIll close this issue here for now bcz this is not a right repo. As we haven't open sourced the bundle relay yet.

Just tested and `getUserStats` also fails although does seem to be an `ethers-flashbots` error, I opened an issue there as well: https://github.com/onbjerg/ethers-flashbots/issues/38.

**Comment by bhakiyakalimuthu** [comment]
@ibhagwan  I misread that you are using this https://github.com/flashbots/ethers-provider-flashbots-bundle.
