### ISSUE TITLE
metamask wallet compromised 

### ISSUE THREAD

**Issue by Kale89** [flashbots/rpc-endpoint#110]
hello dear my metamask wallet is compomised i have joined all my airdrop using that metamask  for the last one year no i am wondering what will happen if i recieve airdrop tokens how to remove them to other wallet please help me in this regard around 300 optimism eth  usdca and op token hacked from my metamask wallet

**Comment by bhakiyakalimuthu** [comment]
Hi please join Flashbots [discord](https://discord.com/invite/flashbots). Request for a help and White-hat team can help you. I'm closing this issue for now.
