### ISSUE TITLE
retry limit

### ISSUE THREAD

**Issue by yeonghow** [flashbots/rpc-endpoint#64]
Hi, is it possible to change the max retry limit of 25?

**Comment by metachris** [comment]
Which retry limit do you mean? And for what use-case?

**Comment by yeonghow** [comment]
"...the call is sent to the Flashbots relay as a private transaction, and submitted as bundles for up to 25 blocks."
This. I would like to lower it to 2 or something so I do not have to wait for 25 blocks to drop my bundle, then I can proceed to submit a new bundle. Imagine buying multiple items on Opensea when everyone is competing to get the lowest price items first.

**Comment by metachris** [comment]
Not currently supported, but I've put it on the feature request list!

**Comment by metachris** [comment]
In the meantime you could send your transactions directly to the relay with `eth_sendPrivateTransaction`: https://docs.flashbots.net/flashbots-auction/searchers/advanced/rpc-endpoint#eth_sendprivatetransaction
