### ISSUE TITLE
https://rpc.flashbots.net/fast  txn fail after 25 blocks,  then mined 90 minutes later

### ISSUE THREAD

**Issue by 8001800** [flashbots/rpc-endpoint#95]
https://rpc.flashbots.net/fast  txn fail after 25 blocks,  then mined 90 minutes later.
( No any changes made at my side after the 25 blocks , no matter gas or endpoint)

Miner is Ethermine.

As per https://protect.flashbots.net/

- > fastMode":true,"seenInMempool":false,"simError":"MaxFeePerGasTooLow"}

maxBlockNumber xxxxxx
Which is far less than the actual block number.

It's not 1st time that Ethermine mined my failed txns after 25 blocks drop in fastmode ,  it happened twice in last 8 hours ,  is this a bug or something else?

(   my Txns were always failed at flashbot normal mode , so all of my 50 +  Txns were through fast mode up to now)

Thanks

**Comment by metachris** [comment]
Could you post the tx hash? One explanation could be that the block it fast first mined in was uncled, and thus the tx becoming public, and free for anyone to mine again.

**Comment by metachris** [comment]
Could you post the tx hash? One explanation could be that the block it fast first mined in was uncled, and thus the tx becoming public, and free for anyone to mine again.

**Comment by 8001800** [comment]
Thanks.  
Here is the result from https://protect.flashbots.net/


{"status":"INCLUDED","hash":"0x......","maxBlockNumber":15342010,"transaction":{"from":"0x....","to":"0x...","gasLimit":"2211378","maxFeePerGas":"9900000000","maxPriorityFeePerGas":"4400000000","nonce":"58","value":"0"},"fastMode":true,"seenInMempool":false,"simError":"MaxFeePerGasTooLow"}

Actual block number 15342124

For privacy, hash number is redacted .

**Comment by Ruteri** [comment]
@8001800 fast mode does not have the 25 blocks limit, the transaction goes into miners' private tx pool and remains there until either included or evicted (miners have their own eviction period).
cc @metachris

**Comment by 8001800** [comment]
I see , thanks a lot.  
Wish this key point could be noted in docs.

**Comment by Ruteri** [comment]
I'll make sure it's in the docs, thanks for flagging it!

**Comment by bhakiyakalimuthu** [comment]
@8001800 Thanks for flagging. Updated the docuements.
