### ISSUE TITLE
Include sanctions checking for regions outside U.S.

### ISSUE THREAD

**Issue by jackturnbull** [flashbots/rpc-endpoint#98]
Hi Flashbots,

I'd originally attempted to submit a PR https://github.com/flashbots/rpc-endpoint/pull/96 without first realising that the contribution guidelines stated that I must first submit an issue. Unfortunately my PR was closed without any rationale on why, nor any pathways to rectify this. While the wording was tongue-in-cheek (I acknowledge) the intent was transparent and I believe that you there is a strong case to be made for expanding the sanctions checking to nations other than the U.S.

My problems with this process so far:

- Your approach to sactions maintenance is completely undocumented.
  - _effect:_ how was I meant to know that this PR isn't helpful? Do you only consider sanctions from the U.S. to be valid?
- Your approach to rectifying this PR is unhelpful.
  - _effect:_ what was the issue with this PR? Why was it closed?

Despite the comments on the PR being spam-like, and brigade-like I would like to make the case to open this PR based on the following:

- AFAIK, Flashbots is an international organisation with members around the world, as noted in #92.
- This is an honest, in essence, attempt to level the playing field on the sanctions handling: I have not invented the sanction address and this is very much a real, legally binding sanction from the UK government. Nor am I attempting to conceal it's weight, it is equally as valid as that of OFAC. It just happens to not be the U.S. government.

While I'd like to be wrong, it feels disappointing to see any project hide behind contribution guidelines for discouraging conversation and to ensure that my next attempt meets all contribution guidelines I am creating this issue before re-raising the PR.

**Comment by come-maiz** [comment]
Your PR wording was tongue-in-cheek, that's non-compliant (a very trendy word this days) with our contribution guidelines. When you come with clear questions in a helpful manner, we will happily receive you. This is clear on everything we do, and necessary for our personal sanity and collective health.

**Comment by jackturnbull** [comment]
Absolutely - and I understand that you need to draw the line at certain communication styles for efficiency, no harm done in that regard.

I would therefore like to propose a couple of clear questions that are hopeully take on face-value, with no malintent:

- Is Flashbots only indending to adhere to sanctions within the U.S.? Rephrase; is not interested in compliance outside of the U.S.?
- Are you able to offer guidance or documentation on which sanctions lists you intend to support, and why?

**Comment by Pandapip1** [comment]
I propose that #99 supersede this issue. The rationale for each is similar, but #99 allows more customizability for the user.

**Comment by jackturnbull** [comment]
Added further comment over here (https://github.com/flashbots/rpc-endpoint/pull/96#issuecomment-1216767913) to be used for people looking back at this in future who may have missed some context on why this was created.

I maintain my stance that on a rational level that the UK sanctions list is as equally valid for inclusion as the US one, and inclusion of one should make the other valid, but I don't believe the Flashbots team want to face this head on. The original PR wase closed due to being "not helpful, for obvious reasons." I would make a straight argument that the content of the code is helpful, written in the style of the repo, cleanly, and with tests and should be merged on its own merit.

But if there is to be no engagement around the content of the code and it's merit (or why it was not valid for inclusion outside of moderation), and nor do I expect there to be any engagement on this open issue, then I won't push it any further and clean this up in the mean-time by closing it.
